name: Nightly CI Dispatcher

on:
  # push:
  #  branches:
  #    - develop
  schedule:
    - cron: "0 0 * * *"

jobs:
  mayastor:
    name: ${{ matrix.repo == 'mayastor-control-plane' && 'mayastor-controller' || matrix.repo }} (${{ matrix.branch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [develop, release/2.11]
        repo: [mayastor, mayastor-control-plane, mayastor-extensions]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/dispatch-and-await
        with:
          token: ${{ secrets.ORG_CI_GITHUB }}
          repo: ${{ matrix.repo }}
          branch: ${{ matrix.branch }}

  rawfile:
    name: rawfile (${{ matrix.branch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [develop]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/dispatch-and-await
        with:
          token: ${{ secrets.ORG_CI_GITHUB }}
          repo: rawfile-localpv
          branch: ${{ matrix.branch }}

  hostpath:
    name: hostpath (${{ matrix.branch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [develop]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/dispatch-and-await
        with:
          token: ${{ secrets.ORG_CI_GITHUB }}
          repo: dynamic-localpv-provisioner
          branch: ${{ matrix.branch }}

  lvm:
    name: lvm (${{ matrix.branch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [develop]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/dispatch-and-await
        with:
          token: ${{ secrets.ORG_CI_GITHUB }}
          repo: lvm-localpv
          branch: ${{ matrix.branch }}

  zfs:
    name: zfs (${{ matrix.branch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [develop]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/dispatch-and-await
        with:
          token: ${{ secrets.ORG_CI_GITHUB }}
          repo: zfs-localpv
          branch: ${{ matrix.branch }}

  nightly-ci:
    name: Collect All Runs
    needs: [mayastor, rawfile, hostpath, lvm, zfs]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Workflow Complete
        if: always()
        run: echo "All matrix jobs have completed!"
